<?php

namespace ContainerS9BaJPs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0wBSLIPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0wBSLIP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0wBSLIP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'competitionRepository' => ['privates', 'App\\Repository\\CompetitionRepository', 'getCompetitionRepositoryService', true],
        ], [
            'Paginator' => '?',
            'competitionRepository' => 'App\\Repository\\CompetitionRepository',
        ]);
    }
}
