<?php

namespace ContainerS9BaJPs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Avk3upCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Avk3upC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Avk3upC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competition' => ['privates', '.errored..service_locator.Avk3upC.App\\Entity\\Competition', NULL, 'Cannot autowire service ".service_locator.Avk3upC": it references class "App\\Entity\\Competition" but no such service exists.'],
            'competitionRepository' => ['privates', 'App\\Repository\\CompetitionRepository', 'getCompetitionRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'competition' => 'App\\Entity\\Competition',
            'competitionRepository' => 'App\\Repository\\CompetitionRepository',
            'entityManager' => '?',
            'mailer' => '?',
        ]);
    }
}
