<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUww335H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUww335H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUww335H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUww335H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUww335H\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uww335H',
    'container.build_id' => '34121d28',
    'container.build_time' => 1677032604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUww335H');
