<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Competition extends \App\Entity\Competition implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'nomCompetition', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'fraisCompetition', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'dateCompetition', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'nbrMaxInscrit', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'etatCompetition', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'tickets'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'nomCompetition', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'fraisCompetition', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'dateCompetition', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'nbrMaxInscrit', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'etatCompetition', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'tickets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Competition $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCompetition(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCompetition', []);

        return parent::getNomCompetition();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCompetition(string $nomCompetition): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCompetition', [$nomCompetition]);

        return parent::setNomCompetition($nomCompetition);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisCompetition(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisCompetition', []);

        return parent::getFraisCompetition();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisCompetition(float $fraisCompetition): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisCompetition', [$fraisCompetition]);

        return parent::setFraisCompetition($fraisCompetition);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCompetition(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCompetition', []);

        return parent::getDateCompetition();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCompetition(\DateTimeInterface $dateCompetition): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCompetition', [$dateCompetition]);

        return parent::setDateCompetition($dateCompetition);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrMaxInscrit(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrMaxInscrit', []);

        return parent::getNbrMaxInscrit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrMaxInscrit(int $nbrMaxInscrit): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrMaxInscrit', [$nbrMaxInscrit]);

        return parent::setNbrMaxInscrit($nbrMaxInscrit);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtatCompetition(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtatCompetition', []);

        return parent::getEtatCompetition();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtatCompetition(string $etatCompetition): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtatCompetition', [$etatCompetition]);

        return parent::setEtatCompetition($etatCompetition);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getTickets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTickets', []);

        return parent::getTickets();
    }

    /**
     * {@inheritDoc}
     */
    public function addTicket(\App\Entity\Ticket $ticket): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTicket', [$ticket]);

        return parent::addTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTicket(\App\Entity\Ticket $ticket): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTicket', [$ticket]);

        return parent::removeTicket($ticket);
    }

}
