<?php

namespace ContainerQi8Cwx1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__KsIxguService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..KsIxgu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..KsIxgu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competition' => ['privates', '.errored..service_locator..KsIxgu.App\\Entity\\Competition', NULL, 'Cannot autowire service ".service_locator..KsIxgu": it references class "App\\Entity\\Competition" but no such service exists.'],
            'competitionRepository' => ['privates', 'App\\Repository\\CompetitionRepository', 'getCompetitionRepositoryService', true],
            'entityManager' => ['privates', '.errored.Q87ZwL4', NULL, 'Cannot determine controller argument for "App\\Controller\\CompetitionController::reserver()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
        ], [
            'competition' => 'App\\Entity\\Competition',
            'competitionRepository' => 'App\\Repository\\CompetitionRepository',
            'entityManager' => '?',
        ]);
    }
}
