<?php

namespace ContainerQi8Cwx1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetitionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..KsIxgu.App\Entity\Competition' shared service.
     *
     * @return \App\Entity\Competition
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..KsIxgu": it references class "App\\Entity\\Competition" but no such service exists.');
    }
}
