<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGbqn7YN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGbqn7YN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGbqn7YN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGbqn7YN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGbqn7YN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gbqn7YN',
    'container.build_id' => '9c130425',
    'container.build_time' => 1676811921,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGbqn7YN');
