<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4cLxwiv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4cLxwiv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4cLxwiv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4cLxwiv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4cLxwiv\App_KernelDevDebugContainer([
    'container.build_hash' => '4cLxwiv',
    'container.build_id' => '5e7677a9',
    'container.build_time' => 1677675324,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4cLxwiv');
