<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS9BaJPs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS9BaJPs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS9BaJPs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS9BaJPs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS9BaJPs\App_KernelDevDebugContainer([
    'container.build_hash' => 'S9BaJPs',
    'container.build_id' => '67c1700e',
    'container.build_time' => 1678291442,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS9BaJPs');
